Repository crt25/collimator, pull requests merged in 2024-11, with the labels that each got.

#41 Improve criteria based analyzers
  backend/src/data-analyzer/ast-walk.ts
  backend/src/data-analyzer/criteria-based-analyzers/calls-function.ts
  backend/src/data-analyzer/criteria-based-analyzers/contains-condition.ts
  backend/src/data-analyzer/criteria-based-analyzers/contains-function-declaration.ts
  backend/src/data-analyzer/criteria-based-analyzers/contains-loop.ts
  backend/src/utilities/is-non-null.ts
Labels: bug, enhancement

#66 [CRT-32] Improve documentation
  docs/_sidebar.md
  docs/identity-management/protocol.excalidraw
  docs/identity-management/protocol.png
  docs/scratch/modifications.md
Labels: documentation

#80 [CRT-5] Solutions API
  backend/prisma/migrations/20241110232123_fix_solution_data/migration.sql
  backend/prisma/schema.prisma
  backend/prisma/seed.ts
  backend/src/api/api.module.ts
  backend/src/api/solutions/dto/create-solution.dto.ts
  backend/src/api/solutions/dto/existing-solution.dto.ts
  backend/src/api/solutions/dto/index.ts
  backend/src/api/solutions/solutions.controller.ts
  backend/src/api/solutions/solutions.module.ts
  backend/src/api/solutions/solutions.service.spec.ts
  backend/src/api/solutions/solutions.service.ts
Labels: enhancement
